[package]
edition = "2021"
name = "libxdo-sys"
version = "0.11.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
license = "MIT"
description = "FFI bindings to libxdo"
readme = "README.md"
repository = "https://github.com/crumblingstatue/rust-libxdo-sys"
keywords = ["X11", "automation", "xdotool", "libxdo", "xdo"]

links = "xdo"
build = "build.rs"

[dependencies]
libc = "0.2.183"
x11rb = { version = "0.13.2", features = ["cursor", "image", "extra-traits", "shm", "xkb", "xtest", "res"] }

